### DISCUSSION TITLE
Расстояние между слайдами компонента Gallery

### DISCUSSION THREAD

**Discussion by kombat-fml** [VKCOM/VKUI#4056] [Q&A] [answered]
Добрый день! Не могу найти где задать расстояние между слайдами. Попытки поиграться padding-ми margin-ми ни к чему не привели. Помогите пожалуйста 🙏🏻

**Comment by inomdzhon** [comment, marked as answer]
Приветствую!

Для реализации твоей задачи надо обернуть каждый слайд в обёртку со следуюищими стиялми

```css
.slide-item-wrapper {
  display: flex;
  padding: 8px; /* отступ вокруг */
  box-sizing: border-box; /* чтобы компенсировать `padding`, т.к. Gallery сверху задаёт `width: 100%` */
}
```

Ниже измененный пример из доки https://vkcom.github.io/VKUI/#/Gallery (атрибут `style` использую для примера, лучше через `className` задавать CSS класс)

```jsx
<Group header={<Header mode="secondary">Sticks right</Header>}>
  <Gallery slideWidth="90%" bullets="dark">
    <div style={{ display: 'flex', padding: 8, boxSizing: 'border-box' }}> // лучше `className="slide-item-wrapper"`
      <div
        style={{
          width: '100%',
          height: '100%',
          backgroundColor: 'var(--vkui--color_background_negative)',
        }}
      />
    </div>
    <div style={{ display: 'flex', padding: 8, boxSizing: 'border-box' }}>
      <img src="https://picsum.photos/1024/640" style={{ width: '100%', height: '100%' }} />
    </div>
    <div style={{ display: 'flex', padding: 8, boxSizing: 'border-box' }}>
      <img src="https://picsum.photos/1024/640" style={{ width: '100%', height: '100%' }} />
    </div>
  </Gallery>
</Group>
```
