### DISCUSSION TITLE
Высота контента Card 100%

### DISCUSSION THREAD

**Discussion by ukqfhf** [VKCOM/VKUI#5882] [Q&A] [answered]
Как управлять высокой компонента `Card`? Из-за наличия еще одного `div` внутри непонятно как реализовать `Card` с высотой X и вертикально отцентрованным контентом без привязки к внутреннему классу `.vkuiCard__in`. Можно ли как-то избежать погружения в детали реализации?

**Comment by SevereCloud** [comment, marked as answer]
Привет, вообще `vkuiCard__in` был удален с версии v5.4.0

### Использование grid

Для решения твоей задачи очень легко использовать `display: grid`

```css
.block {
  flex-grow: 1; /* если внешний блок это флекс */
  height: 100%;  /* если у внешнего блока height: 100% */

  width: 100%;
  display: grid;
}

 /* растягиваемся и центрируемся */
.content {
  ...
}
```

```tsx
<div className="block">
  <Card>
    <div className="content">content</div>
  </Card>
</div>
```

<details><summary>Скриншот</summary>
<p>

<img width="622" alt="image" src="https://github.com/VKCOM/VKUI/assets/14944123/c129227d-ab30-46d0-bdb5-0ea450641adf">

</p>
</details> 


У этого подхода есть минус - [браузерная поддержка](https://caniuse.com/css-grid)

### Использование flex

Есть вариант с `display: flex` который слегка нарушает инкапсуляцию компонента, но нет проблем с браузерной поддержкой 

```css
.block {
  display: flex;
}

 /* stylelint-disable-next-line selector-max-universal -- растягиваем контент внутри .block */
.block > * {
  flex-grow: 1; 
}
```
