### ISSUE TITLE
[Bug][Crit] В Root создается лишний div

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1981]
**Описание**
https://github.com/VKCOM/VKUI/blob/1b8bc148b85c0ba2bcaede1642b77ab65c134226/src/components/Root/Root.tsx#L135-L137

Если в Panel передать Placeholder stretched, то получим вот такую штуку

<img src="https://user-images.githubusercontent.com/11076888/137907218-3b2346cf-084b-4756-bedc-35370f54e9d2.png" width="400" />

**Версия библиотеки**
v4.18.0

**Comment by eolme** [comment]
Чинится вот так:
```css
.vkuiRoot__view > div {
  width: 100%;
  height: 100%;
}
```
