### ISSUE TITLE
[Feature] Nowrap в Typography

### ISSUE THREAD

**Issue by Lunarshade1990** [VKCOM/VKUI#2084]
Добавьте, пожалуйста, в компонентах из раздела Typography проперти для запрета переноса текста c  text-overflow = ellipsis, чтобы не выглядело вот так:
![image](https://user-images.githubusercontent.com/41172386/141703099-39b510f6-9339-4cad-8c5f-36224e2f96ba.png)
Назначение нужных стилей напрямую компонентам не работает

**Comment by eugpoloz** [comment]
Привет! Типографические компоненты используются во многих местах, где перенос текста нужен, поэтому для них мы так сделать точно не можем.

Попробуй внутри своего компонента дать типографическому класс, например:

```ts
<Text weight="medium" className="NoOverflow">Твой текст</Text>
```

И потом в стилях для этого компонента прописать ellipsis:
```css
.NoOverflow {
  overflow: hidden;
  white-space: nowrap; /* без этих двух свойств text-overflow:ellipsis; не сработает */
  text-overflow: ellipsis;
}
```
