### ISSUE TITLE
[Feature][Gallery] An option to disable slide transition for gallery component

### ISSUE THREAD

**Issue by CursedWizard** [VKCOM/VKUI#2186]
I use the component as a carousel of pages basically and would like to have a non-zero 
slide as a default one, but seeing the shifting animation every time the component mounts 
is quite irritating

**Comment by thoughtspile** [comment]
Дубликат #2117. Логика для перехода к `initialSlideIndex` без анимации есть, но работает нестабильно. Пока используем воркераунд:

```css
.vkuiGallery--noAnimation .vkuiGallery__layer {
  transition: none !important;
}
```

```jsx
const [animation, setAnimation] = useState(false);
useEffect(() => {
  requestAnimationFrame(() => {
    requestAnimationFrame(() => setAnimation(true));
  });
}, []);

<Gallery className={animation ? null: 'vkuiGallery--noAnimation'} />
```
