### ISSUE TITLE
[Breaking changes] Окончательно отказаться от `Appearance` в пользу `vkui-tokens`

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#2384]
- [ ] переводим все компоненты на токены
- [ ] отказываемся в CSS от оформления привязанное к платформенному классу в пользу токенов из [vkui-tokens](https://github.com/VKCOM/vkui-tokens)
    ```css
    /* ❌  bad */
    .Component {
      border-radius: 8px;
    }
    .Component--ios {
      border-radius: 10px;
    }
    /* ✅  good */
    .Component {
      border-radius: var(--vkui--size_border_radius--regular);
    }         
    ```
- [ ] удаляем лишние селекторы, остававшиеся для обратной совместимости
- [ ] решаем вопрос с наследованием темы (см. [Платформы и темы в документации](https://vkcom.github.io/VKUI/#/PlatformsAndThemes) => Наследование темы). Вероятно, потом стоит это упомянуть и в https://github.com/VKCOM/VKUI/issues/2351
