### ISSUE TITLE
[Bug]: Поправить токенизацию CardGrid

### ISSUE THREAD

**Issue by fedorov-xyz** [VKCOM/VKUI#3506]
### Описание

1. Не токенизировано значение `4px`. Полагаю, что оно должно быть в половину значения от токена ниже.

![image](https://user-images.githubusercontent.com/25563268/197784455-669d594b-b7b1-4daa-9037-34a2dd23ed8e.png)

2. Неверные отступы слева и справа.

```css
.Group--card .CardGrid {
  padding-left: 8px;
  padding-right: 8px;
}
```

Должны быть токеном `vkui--size_base_padding_horizontal--regular`, чтобы находясь в группе нормально выравнивались с шапкой.

### Версия

latest
