### ISSUE TITLE
[Bug]: Добавить негативный отступ для конструкции Group > Tappable > Header

### ISSUE THREAD

**Issue by fedorov-xyz** [VKCOM/VKUI#3508]
### Описание

Сейчас в стилях есть такой код, который делает визуальную компенсацию.

```css
.Group--card > .Group__inner > .Header:not(.Header--mode-tertiary):first-child {
  margin-top: -4px;
}
```

Если обернуть `<Header />` в `<Tappable />` и передать в `<Group />`, правило перестанет работать.

### Версия

latest
