### ISSUE TITLE
Сделать Checkbox с обратным расположением элементов

### ISSUE THREAD

**Issue by ciricc** [VKCOM/VKUI#357]
Checkbox'ам не хватает возможности изменить расположение бокса и лейбла.
Видел такое в Android'овских приложениях.

```javascript
<Checkbox float="right">Label</Checkbox>
```

```css
.Checkbox.Checkbox--right .Checkbox__container {
  flex-direction: row-reverse;
}
```
