### ISSUE TITLE
[v4] [Bug]: Чип с длинным текстом вылезает за пределы контейнера в ChipsInput

### ISSUE THREAD

**Issue by fedorov-xyz** [VKCOM/VKUI#3643]
### Описание

<img width="550" alt="image" src="https://user-images.githubusercontent.com/25563268/203535336-d004b943-00c0-4209-9a0d-afb12afc4628.png">

Фикс: 

```css
.vkuiChipsInputBase__chip {
  max-width: calc(100% - 4px);
}
```

### Версия

latest
